name: sway-environment
type: apt
source:
  packages:
    - sway
    - waybar
    - swaylock
    - swayidle
    - wofi
    - sway-notification-center
    - nm-connection-editor
    - fonts-font-awesome
